"""empty message

Revision ID: 160cc4c35a8e
Revises: 2acfe1e7e387
Create Date: 2025-09-21 08:26:10.743852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160cc4c35a8e'
down_revision = '2acfe1e7e387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_membersa',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projectsa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    with op.batch_alter_table('projectsa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_type', sa.String(length=20), nullable=True))

    with op.batch_alter_table('tasksa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasksa', schema=None) as batch_op:
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('progress')

    with op.batch_alter_table('projectsa', schema=None) as batch_op:
        batch_op.drop_column('project_type')

    op.drop_table('project_membersa')
    # ### end Alembic commands ###
