"""empty message

Revision ID: 285edb01069a
Revises: 8534df1a82f0
Create Date: 2025-09-26 16:24:41.221148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '285edb01069a'
down_revision = '8534df1a82f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # For SQLite, adding a NOT NULL column requires a server_default
    with op.batch_alter_table('helpdesk_queries', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('status', sa.String(length=30), nullable=False, server_default='Not started')
        )
    # If desired, you could drop the server_default in databases that support it.
    # SQLite does not support dropping a column default easily in-place, so we keep it.
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_queries', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
