"""New changes after database reset

Revision ID: 44a10bf88779
Revises: 
Create Date: 2025-06-24 12:48:06.734398

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '44a10bf88779'
down_revision = None
branch_labels = None
depends_on = None


def _tables_exist(conn):
    return set(inspect(conn).get_table_names())


def upgrade():
    conn = op.get_bind()
    existing = _tables_exist(conn)
    # ### commands auto generated by Alembic - please adjust! ###
    if 'book_allocations' not in existing:
        op.create_table('book_allocations',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('school_name', sa.String(length=100), nullable=False),
            sa.Column('school_province', sa.String(length=100), nullable=False),
            sa.Column('books_allocated', sa.String(length=500), nullable=True),
            sa.Column('timestamp', sa.DateTime(), nullable=True),
            sa.Column('allocated_by', sa.String(length=100), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('book_allocations', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_book_allocations_timestamp'), ['timestamp'], unique=False)

    if 'report' not in existing:
        op.create_table('report',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('employee_name', sa.String(length=100), nullable=False),
            sa.Column('department', sa.String(length=100), nullable=False),
            sa.Column('this_week', sa.Text(), nullable=False),
            sa.Column('next_week', sa.Text(), nullable=False),
            sa.Column('date_submitted', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    if 'user' not in existing:
        op.create_table('user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=64), nullable=False),
            sa.Column('email', sa.String(length=120), nullable=False),
            sa.Column('password_hash', sa.String(length=256), nullable=True),
            sa.Column('firstname', sa.String(length=64), nullable=False),
            sa.Column('lastname', sa.String(length=64), nullable=False),
            sa.Column('userRole', sa.String(length=64), nullable=False),
            sa.Column('department', sa.String(length=120), nullable=True),
            sa.Column('province', sa.String(length=120), nullable=True),
            sa.Column('privileges', sa.JSON(), nullable=True),
            sa.Column('last_seen', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_department'), ['department'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
            batch_op.create_index(batch_op.f('ix_user_firstname'), ['firstname'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_lastname'), ['lastname'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_province'), ['province'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_userRole'), ['userRole'], unique=False)
            batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    if 'workspace' not in existing:
        op.create_table('workspace',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('created_by', sa.Integer(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if 'project' not in existing:
        op.create_table('project',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('workspace_id', sa.Integer(), nullable=False),
            sa.Column('parent_id', sa.Integer(), nullable=True),
            sa.Column('start_date', sa.DateTime(), nullable=True),
            sa.Column('end_date', sa.DateTime(), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=True),
            sa.ForeignKeyConstraint(['parent_id'], ['project.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    if 'workspace_membership' not in existing:
        op.create_table('workspace_membership',
            sa.Column('user_id', sa.Integer(), nullable=True),
            sa.Column('workspace_id', sa.Integer(), nullable=True),
            sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
            sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], )
        )
    if 'task' not in existing:
        op.create_table('task',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('title', sa.String(length=100), nullable=False),
            sa.Column('description', sa.Text(), nullable=True),
            sa.Column('assigned_to', sa.Integer(), nullable=True),
            sa.Column('project_id', sa.Integer(), nullable=True),
            sa.Column('parent_id', sa.Integer(), nullable=True),
            sa.Column('start_date', sa.DateTime(), nullable=True),
            sa.Column('due_date', sa.DateTime(), nullable=True),
            sa.Column('status', sa.String(length=50), nullable=True),
            sa.ForeignKeyConstraint(['assigned_to'], ['user.id'], ),
            sa.ForeignKeyConstraint(['parent_id'], ['task.id'], ),
            sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    op.drop_table('workspace_membership')
    op.drop_table('project')
    op.drop_table('workspace')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_userRole'))
        batch_op.drop_index(batch_op.f('ix_user_province'))
        batch_op.drop_index(batch_op.f('ix_user_lastname'))
        batch_op.drop_index(batch_op.f('ix_user_firstname'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_department'))

    op.drop_table('user')
    op.drop_table('report')
    with op.batch_alter_table('book_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_allocations_timestamp'))

    op.drop_table('book_allocations')
    # ### end Alembic commands ###
