"""empty message

Revision ID: 5bd531fe2846
Revises: 1e6e270dd191
Create Date: 2025-08-03 04:37:38.844053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd531fe2846'
down_revision = '1e6e270dd191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('perfomancetargets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('smartlearning_registrations_monthly_target', sa.Integer(), nullable=True),
    sa.Column('smartlearning_registrations_daily_target', sa.Integer(), nullable=True),
    sa.Column('smartlearning_unique_subscribers_monthly_target', sa.Integer(), nullable=True),
    sa.Column('smartlearning_unique_subscribers_daily_target', sa.Integer(), nullable=True),
    sa.Column('ask_akello_users_monthly_target', sa.Integer(), nullable=True),
    sa.Column('ask_akello_users_daily_target', sa.Integer(), nullable=True),
    sa.Column('library_registrations_monthly_target', sa.Integer(), nullable=True),
    sa.Column('library_registrations_daily_target', sa.Integer(), nullable=True),
    sa.Column('library_unique_users_monthly_target', sa.Integer(), nullable=True),
    sa.Column('library_unique_users_daily_target', sa.Integer(), nullable=True),
    sa.Column('overall_active30_target', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perfomancetargets')
    # ### end Alembic commands ###
