"""add collateral items table

Revision ID: 657d9e7f8894
Revises: a2f4d38ea93a
Create Date: 2025-11-07 11:29:53.286997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657d9e7f8894'
down_revision = 'a2f4d38ea93a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collateral_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collateral_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collateral_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collateral_items_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collateral_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_items_created_at'))

    op.drop_table('collateral_items')
    # ### end Alembic commands ###
