"""empty message

Revision ID: 8534df1a82f0
Revises: 160cc4c35a8e
Create Date: 2025-09-26 16:00:31.653509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8534df1a82f0'
down_revision = '160cc4c35a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpdesk_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_title', sa.String(length=200), nullable=False),
    sa.Column('query_description', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('query_type', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('helpdesk_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_helpdesk_queries_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_helpdesk_queries_timestamp'))

    op.drop_table('helpdesk_queries')
    # ### end Alembic commands ###
