"""sales and marketing feature — safe index additions only

Revision ID: 88a51ab2a25e
Revises: p6q7r8s9t0u1
Create Date: 2026-06-10 22:36:12.259035

The autogenerated revision included unrelated projectsa/tasksa FK changes that fail on
SQLite (unnamed constraints). Sales & Marketing tables were already created in o5p5p6q7r8s9t0;
this revision only adds optional indexes if they are missing.
"""

from alembic import op
import sqlalchemy as sa


revision = "88a51ab2a25e"
down_revision = "p6q7r8s9t0u1"
branch_labels = None
depends_on = None


def _table_exists(name):
    bind = op.get_bind()
    return name in sa.inspect(bind).get_table_names()


def _index_exists(table, index_name):
    bind = op.get_bind()
    if not _table_exists(table):
        return True
    indexes = sa.inspect(bind).get_indexes(table)
    return any(ix.get("name") == index_name for ix in indexes)


def _create_index_if_missing(table, index_name, columns):
    if not _table_exists(table):
        return
    if _index_exists(table, index_name):
        return
    op.create_index(index_name, table, columns)


def upgrade():
    # Drop stale Alembic temp table if a prior failed batch migration left it behind.
    if _table_exists("_alembic_tmp_projectsa"):
        op.drop_table("_alembic_tmp_projectsa")

    _create_index_if_missing(
        "sales_marketing_email_campaign_recipients",
        "ix_sales_marketing_email_campaign_recipients_stakeholder_id",
        ["stakeholder_id"],
    )
    _create_index_if_missing(
        "sales_marketing_submission_rate_limits",
        "ix_sales_marketing_submission_rate_limits_submitted_at",
        ["submitted_at"],
    )


def downgrade():
    if _table_exists("sales_marketing_submission_rate_limits") and _index_exists(
        "sales_marketing_submission_rate_limits",
        "ix_sales_marketing_submission_rate_limits_submitted_at",
    ):
        op.drop_index(
            "ix_sales_marketing_submission_rate_limits_submitted_at",
            table_name="sales_marketing_submission_rate_limits",
        )
    if _table_exists("sales_marketing_email_campaign_recipients") and _index_exists(
        "sales_marketing_email_campaign_recipients",
        "ix_sales_marketing_email_campaign_recipients_stakeholder_id",
    ):
        op.drop_index(
            "ix_sales_marketing_email_campaign_recipients_stakeholder_id",
            table_name="sales_marketing_email_campaign_recipients",
        )
