"""empty message

Revision ID: 8a8631e40149
Revises: 9a5c2ec7aaec
Create Date: 2025-06-30 00:58:01.732401

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = '8a8631e40149'
down_revision = '9a5c2ec7aaec'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    if 'scorecard' in inspect(conn).get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scorecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_focus_area', sa.String(length=100), nullable=False),
    sa.Column('strategic_objective', sa.String(length=200), nullable=False),
    sa.Column('performance_measure', sa.String(length=200), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=100), nullable=False),
    sa.Column('target', sa.String(length=100), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('employee_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    if 'scorecard' not in inspect(conn).get_table_names():
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scorecard')
    # ### end Alembic commands ###
