"""Description of new changes

Revision ID: 900c2e62da0e
Revises: c4d9e8a1f2b3
Create Date: 2026-04-23 15:44:46.299691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900c2e62da0e'
down_revision = 'c4d9e8a1f2b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('school_visit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('asl_school_id', sa.String(length=50), nullable=False),
    sa.Column('library_id', sa.String(length=50), nullable=False),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('checkin_at', sa.DateTime(), nullable=False),
    sa.Column('checkout_at', sa.DateTime(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('checkin_latitude', sa.Float(), nullable=True),
    sa.Column('checkin_longitude', sa.Float(), nullable=True),
    sa.Column('location_text', sa.String(length=255), nullable=True),
    sa.Column('location_source', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('school_visit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_school_visit_logs_checkin_at'), ['checkin_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_visit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_visit_logs_status'), ['status'], unique=False)
        batch_op.create_index('ix_school_visit_logs_user_checkin_desc', ['user_id', 'checkin_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_visit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_school_visit_logs_user_status', ['user_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_school_visit_logs_username'), ['username'], unique=False)

    with op.batch_alter_table('projectsa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projectsa_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectsa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projectsa_owner_id'))

    with op.batch_alter_table('school_visit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_username'))
        batch_op.drop_index('ix_school_visit_logs_user_status')
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_user_id'))
        batch_op.drop_index('ix_school_visit_logs_user_checkin_desc')
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_checkin_at'))

    op.drop_table('school_visit_logs')
    # ### end Alembic commands ###
