"""Description of new changes

Revision ID: 900c2e62da0e
Revises: c4d9e8a1f2b3
Create Date: 2026-04-23 15:44:46.299691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '900c2e62da0e'
down_revision = 'c4d9e8a1f2b3'
branch_labels = None
depends_on = None


def _table_exists(table_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return table_name in inspector.get_table_names()


def _index_names(table_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {index['name'] for index in inspector.get_indexes(table_name)}


def _foreign_key_names(table_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return {fk.get('name') for fk in inspector.get_foreign_keys(table_name) if fk.get('name')}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not _table_exists('school_visit_logs'):
        op.create_table('school_visit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=100), nullable=False),
        sa.Column('asl_school_id', sa.String(length=50), nullable=False),
        sa.Column('library_id', sa.String(length=50), nullable=False),
        sa.Column('school_name', sa.String(length=255), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('checkin_at', sa.DateTime(), nullable=False),
        sa.Column('checkout_at', sa.DateTime(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('checkin_latitude', sa.Float(), nullable=True),
        sa.Column('checkin_longitude', sa.Float(), nullable=True),
        sa.Column('location_text', sa.String(length=255), nullable=True),
        sa.Column('location_source', sa.String(length=20), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
        )

    existing_indexes = _index_names('school_visit_logs')
    with op.batch_alter_table('school_visit_logs', schema=None) as batch_op:
        if 'ix_school_visit_logs_checkin_at' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_school_visit_logs_checkin_at'), ['checkin_at'], unique=False)
        if 'ix_school_visit_logs_created_at' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_school_visit_logs_created_at'), ['created_at'], unique=False)
        if 'ix_school_visit_logs_status' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_school_visit_logs_status'), ['status'], unique=False)
        if 'ix_school_visit_logs_user_checkin_desc' not in existing_indexes:
            batch_op.create_index('ix_school_visit_logs_user_checkin_desc', ['user_id', 'checkin_at'], unique=False)
        if 'ix_school_visit_logs_user_id' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_school_visit_logs_user_id'), ['user_id'], unique=False)
        if 'ix_school_visit_logs_user_status' not in existing_indexes:
            batch_op.create_index('ix_school_visit_logs_user_status', ['user_id', 'status'], unique=False)
        if 'ix_school_visit_logs_username' not in existing_indexes:
            batch_op.create_index(batch_op.f('ix_school_visit_logs_username'), ['username'], unique=False)

    if _table_exists('projectsa'):
        existing_projectsa_indexes = _index_names('projectsa')
        existing_projectsa_fks = _foreign_key_names('projectsa')
        with op.batch_alter_table('projectsa', schema=None) as batch_op:
            if 'ix_projectsa_owner_id' not in existing_projectsa_indexes:
                batch_op.create_index(batch_op.f('ix_projectsa_owner_id'), ['owner_id'], unique=False)
            if not any(name and 'owner_id' in name for name in existing_projectsa_fks):
                batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projectsa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_projectsa_owner_id'))

    with op.batch_alter_table('school_visit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_username'))
        batch_op.drop_index('ix_school_visit_logs_user_status')
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_user_id'))
        batch_op.drop_index('ix_school_visit_logs_user_checkin_desc')
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_status'))
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_school_visit_logs_checkin_at'))

    op.drop_table('school_visit_logs')
    # ### end Alembic commands ###
