"""empty message

Revision ID: 989a79097512
Revises: 285edb01069a
Create Date: 2025-09-29 00:29:47.225073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '989a79097512'
down_revision = '285edb01069a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('akello_sim_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('request_collateral', sa.Boolean(), nullable=True),
    sa.Column('collateral_items', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('akello_sim_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_akello_sim_events_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('akello_sim_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_akello_sim_events_timestamp'))

    op.drop_table('akello_sim_events')
    # ### end Alembic commands ###
