"""empty message

Revision ID: 993ff536cf48
Revises: 5bd531fe2846
Create Date: 2025-08-03 04:42:05.060352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993ff536cf48'
down_revision = '5bd531fe2846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfomancetargets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_by', sa.String(length=100), nullable=False))
        batch_op.create_index(batch_op.f('ix_perfomancetargets_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('perfomancetargets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_perfomancetargets_timestamp'))
        batch_op.drop_column('updated_by')
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
