"""Add user activity monitoring models

Revision ID: a18b44ef72ee
Revises: 989a79097512
Create Date: 2025-10-03 16:44:13.461765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a18b44ef72ee'
down_revision = '989a79097512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_path', sa.String(length=500), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=True),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('unique_visitors', sa.Integer(), nullable=True),
    sa.Column('avg_response_time_ms', sa.Float(), nullable=True),
    sa.Column('last_visited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_analytics', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_analytics_last_visited'), ['last_visited'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_analytics_url_path'), ['url_path'], unique=False)

    op.create_table('active_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('first_seen', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_activity_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_active_sessions_first_seen'), ['first_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_last_seen'), ['last_seen'], unique=False)
        batch_op.create_index(batch_op.f('ix_active_sessions_session_id'), ['session_id'], unique=True)

    op.create_table('user_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('session_id', sa.String(length=128), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=100), nullable=False),
    sa.Column('url_path', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_activities_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_activities_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_activities_timestamp'))
        batch_op.drop_index(batch_op.f('ix_user_activities_session_id'))

    op.drop_table('user_activities')
    with op.batch_alter_table('active_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_active_sessions_session_id'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_last_seen'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_is_active'))
        batch_op.drop_index(batch_op.f('ix_active_sessions_first_seen'))

    op.drop_table('active_sessions')
    with op.batch_alter_table('page_analytics', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_analytics_url_path'))
        batch_op.drop_index(batch_op.f('ix_page_analytics_last_visited'))

    op.drop_table('page_analytics')
    # ### end Alembic commands ###
