"""Description of new changes

Revision ID: a4f490e90d0e
Revises: add_tickets_email
Create Date: 2026-03-06 15:48:12.742163

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a4f490e90d0e'
down_revision = 'add_tickets_email'
branch_labels = None
depends_on = None


def _schema_state(bind):
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())
    columns = {
        table: {col["name"] for col in inspector.get_columns(table)}
        for table in tables
    }
    return tables, columns


def upgrade():
    bind = op.get_bind()
    tables, columns = _schema_state(bind)

    # ### commands auto generated by Alembic - please adjust! ###
    if 'branding_items' not in tables:
        op.create_table('branding_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('item_type', sa.String(length=80), nullable=False),
    sa.Column('quantity_available', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform', 'item_type', name='uq_branding_platform_type')
    )
        with op.batch_alter_table('branding_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_branding_items_platform'), ['platform'], unique=False)
        tables.add('branding_items')

    if 'branding_requests' not in tables:
        op.create_table('branding_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_username', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=40), nullable=False),
    sa.Column('item_type', sa.String(length=80), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=True),
    sa.Column('return_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('branding_requests', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_branding_requests_platform'), ['platform'], unique=False)
        tables.add('branding_requests')

    if 'collateral_items' not in tables:
        op.create_table('collateral_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collateral_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('collateral_items', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_collateral_items_created_at'), ['created_at'], unique=False)
        tables.add('collateral_items')

    if 'tickets' not in tables:
        op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('message_id', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('tickets', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_tickets_message_id'), ['message_id'], unique=True)
        tables.add('tickets')

    if 'app_settings' not in tables:
        op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('app_settings', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_app_settings_setting_key'), ['setting_key'], unique=True)
        tables.add('app_settings')

    if 'book_allocation_requests' not in tables:
        op.create_table('book_allocation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_username', sa.String(length=100), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('school_province', sa.String(length=100), nullable=False),
    sa.Column('school_grade', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_allocation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_allocation_id'], ['book_allocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('book_allocation_requests', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_book_allocation_requests_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_book_allocation_requests_requester_username'), ['requester_username'], unique=False)
            batch_op.create_index(batch_op.f('ix_book_allocation_requests_status'), ['status'], unique=False)
        tables.add('book_allocation_requests')

    if 'branding_actions' not in tables:
        op.create_table('branding_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('actor_username', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['branding_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('branding_actions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_branding_actions_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_branding_actions_request_id'), ['request_id'], unique=False)
        tables.add('branding_actions')

    if 'champion_school_requests' not in tables:
        op.create_table('champion_school_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('champion_school_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=True),
    sa.Column('asl_school_id', sa.String(length=50), nullable=True),
    sa.Column('library_school_id', sa.String(length=50), nullable=True),
    sa.Column('school_name', sa.String(length=255), nullable=False),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['champion_school_id'], ['championschools.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('champion_school_requests', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_champion_school_requests_champion_school_id'), ['champion_school_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_champion_school_requests_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_champion_school_requests_requested_by_user_id'), ['requested_by_user_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_champion_school_requests_status'), ['status'], unique=False)
        tables.add('champion_school_requests')

    if 'collateral_requests' not in tables:
        op.create_table('collateral_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collateral_item_id', sa.Integer(), nullable=False),
    sa.Column('requester_username', sa.String(length=100), nullable=False),
    sa.Column('event_details', sa.Text(), nullable=False),
    sa.Column('needed_by_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collateral_item_id'], ['collateral_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('collateral_requests', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_collateral_requests_created_at'), ['created_at'], unique=False)
        tables.add('collateral_requests')

    if 'notifications' not in tables:
        op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['helpdesk_queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('notifications', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_read'), ['read'], unique=False)
            batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        tables.add('notifications')

    if 'query_assignees' not in tables:
        op.create_table('query_assignees',
    sa.Column('query_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['query_id'], ['helpdesk_queries.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('query_id', 'user_id')
        )
        tables.add('query_assignees')

    if 'task_assigneesa' not in tables:
        op.create_table('task_assigneesa',
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasksa.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('task_id', 'user_id')
        )
        tables.add('task_assigneesa')

    game_user_cols = columns.get('game_users', set())
    if 'game_users' in tables and ('age_range' not in game_user_cols or 'phone_number' not in game_user_cols):
        with op.batch_alter_table('game_users', schema=None) as batch_op:
            if 'age_range' not in game_user_cols:
                batch_op.add_column(sa.Column('age_range', sa.String(length=50), nullable=True))
            if 'phone_number' not in game_user_cols:
                batch_op.add_column(sa.Column('phone_number', sa.String(length=20), nullable=True))
            batch_op.alter_column('age',
                   existing_type=sa.INTEGER(),
                   nullable=False)
            batch_op.drop_index(batch_op.f('ix_game_users_username'))
            batch_op.create_index(batch_op.f('ix_game_users_username'), ['username'], unique=True)

    game_cols = columns.get('games', set())
    if 'games' in tables and ('age_range' not in game_cols or 'difficulty_level' not in game_cols):
        with op.batch_alter_table('games', schema=None) as batch_op:
            if 'age_range' not in game_cols:
                batch_op.add_column(sa.Column('age_range', sa.String(length=20), nullable=True))
            if 'difficulty_level' not in game_cols:
                batch_op.add_column(sa.Column('difficulty_level', sa.String(length=20), nullable=True))

    if 'helpdesk_queries' in tables and 'resolved_at' not in columns.get('helpdesk_queries', set()):
        with op.batch_alter_table('helpdesk_queries', schema=None) as batch_op:
            batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('helpdesk_queries', schema=None) as batch_op:
        batch_op.drop_column('resolved_at')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_column('difficulty_level')
        batch_op.drop_column('age_range')

    with op.batch_alter_table('game_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_users_username'))
        batch_op.create_index(batch_op.f('ix_game_users_username'), ['username'], unique=False)
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('phone_number')
        batch_op.drop_column('age_range')

    op.drop_table('task_assigneesa')
    op.drop_table('query_assignees')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('collateral_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_requests_created_at'))

    op.drop_table('collateral_requests')
    with op.batch_alter_table('champion_school_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_champion_school_requests_status'))
        batch_op.drop_index(batch_op.f('ix_champion_school_requests_requested_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_champion_school_requests_created_at'))
        batch_op.drop_index(batch_op.f('ix_champion_school_requests_champion_school_id'))

    op.drop_table('champion_school_requests')
    with op.batch_alter_table('branding_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branding_actions_request_id'))
        batch_op.drop_index(batch_op.f('ix_branding_actions_created_at'))

    op.drop_table('branding_actions')
    with op.batch_alter_table('book_allocation_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_allocation_requests_status'))
        batch_op.drop_index(batch_op.f('ix_book_allocation_requests_requester_username'))
        batch_op.drop_index(batch_op.f('ix_book_allocation_requests_created_at'))

    op.drop_table('book_allocation_requests')
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_settings_setting_key'))

    op.drop_table('app_settings')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_message_id'))

    op.drop_table('tickets')
    with op.batch_alter_table('collateral_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_items_created_at'))

    op.drop_table('collateral_items')
    with op.batch_alter_table('branding_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branding_requests_platform'))

    op.drop_table('branding_requests')
    with op.batch_alter_table('branding_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_branding_items_platform'))

    op.drop_table('branding_items')
    # ### end Alembic commands ###
