"""empty message

Revision ID: a7016ca440af
Revises: bbe95a16fc86
Create Date: 2025-07-20 12:21:30.031841

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a7016ca440af'
down_revision = 'bbe95a16fc86'
branch_labels = None
depends_on = None


def upgrade():
    conn = op.get_bind()
    existing_tables = set(inspect(conn).get_table_names())
    # ### commands auto generated by Alembic - please adjust! ###
    if 'championschools' not in existing_tables:
        op.create_table('championschools',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('firstname', sa.String(length=100), nullable=False),
            sa.Column('lastname', sa.String(length=100), nullable=False),
            sa.Column('province', sa.String(length=100), nullable=False),
            sa.Column('schools', sa.Text(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
    user_cols = [c['name'] for c in inspect(conn).get_columns('user')]
    if 'avatar_filename' in user_cols:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.drop_column('avatar_filename')

    # ### end Alembic commands ###


def downgrade():
    conn = op.get_bind()
    user_cols = [c['name'] for c in inspect(conn).get_columns('user')]
    if 'avatar_filename' not in user_cols:
        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.add_column(sa.Column('avatar_filename', sa.VARCHAR(length=256), nullable=True))
    if 'championschools' in inspect(conn).get_table_names():
        op.drop_table('championschools')
    # ### end Alembic commands ###
