"""Add phone_number to game_users

Revision ID: add_phone_number_game_users
Revises: add_book_allocation_requests
Create Date: 2025-12-04 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_phone_number_game_users'
down_revision = 'add_book_allocation_requests'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_users', 'phone_number')
    # ### end Alembic commands ###

