"""Add book_allocation_requests table

Revision ID: add_book_allocation_requests
Revises: 0362a438d8c
Create Date: 2025-12-04 10:10:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'add_book_allocation_requests'
down_revision = '0362a438d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_allocation_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_username', sa.String(length=100), nullable=False),
    sa.Column('school_name', sa.String(length=100), nullable=False),
    sa.Column('school_province', sa.String(length=100), nullable=False),
    sa.Column('school_grade', sa.String(length=50), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('converted_to_allocation_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['converted_to_allocation_id'], ['book_allocations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_allocation_requests_created_at'), 'book_allocation_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_book_allocation_requests_requester_username'), 'book_allocation_requests', ['requester_username'], unique=False)
    op.create_index(op.f('ix_book_allocation_requests_status'), 'book_allocation_requests', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_allocation_requests_status'), table_name='book_allocation_requests')
    op.drop_index(op.f('ix_book_allocation_requests_requester_username'), table_name='book_allocation_requests')
    op.drop_index(op.f('ix_book_allocation_requests_created_at'), table_name='book_allocation_requests')
    op.drop_table('book_allocation_requests')
    # ### end Alembic commands ###

