"""empty message

Revision ID: e96aac346ea4
Revises: 993ff536cf48
Create Date: 2025-08-18 00:41:24.285208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e96aac346ea4'
down_revision = '993ff536cf48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weekly_report',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('week_start', sa.String(length=20), nullable=False),
    sa.Column('work_done', sa.Text(), nullable=False),
    sa.Column('work_next', sa.Text(), nullable=False),
    sa.Column('challenges', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weekly_report')
    # ### end Alembic commands ###
