"""added collateral items table

Revision ID: f2600506396d
Revises: 657d9e7f8894
Create Date: 2025-11-07 11:54:11.882164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2600506396d'
down_revision = '657d9e7f8894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collateral_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collateral_item_id', sa.Integer(), nullable=False),
    sa.Column('requester_username', sa.String(length=100), nullable=False),
    sa.Column('event_details', sa.Text(), nullable=False),
    sa.Column('needed_by_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=100), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collateral_item_id'], ['collateral_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('collateral_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collateral_requests_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collateral_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collateral_requests_created_at'))

    op.drop_table('collateral_requests')
    # ### end Alembic commands ###
